apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
spec:
  selector:
    matchLabels:
      run: controller
  replicas: 1
  template:
    metadata:
      labels:
        run: controller
    spec:
      containers:
        - name: controller
          image: skirkyn/controller
          ports:
          - containerPort: 50000
---
apiVersion: v1
kind: Service
metadata:
  name: controller
  labels:
    run: controller
spec:
  ports:
    - port: 50000
      protocol: TCP
  selector:
    run: controller
