apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
spec:
  selector:
    matchLabels:
      run: worker
  replicas: 3
  template:
    metadata:
      labels:
        run: worker
    spec:
      containers:
        - name: worker
          image: skirkyn/worker

